joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel
      deadman_buttons: [5]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        angular-z:
          axis: 2
          scale: 1.0
          offset: 0.0

    joy_priority:
      type: action
      interface_type: twist_mux_msgs/action/JoyPriority
      action_name: joy_priority_action
      buttons: [0]

    joy_turbo_decrease:
      type: action
      interface_type: twist_mux_msgs/action/JoyTurbo
      action_name: joy_turbo_decrease
      buttons: [1, 4, 5]

    joy_turbo_increase:
      type: action
      interface_type: twist_mux_msgs/action/JoyTurbo
      action_name: joy_turbo_increase
      buttons: [3, 4, 5]

    joy_turbo_angular_decrease:
      type: action
      interface_type: twist_mux_msgs/action/JoyTurbo
      action_name: joy_turbo_angular_decrease
      buttons: [0, 4, 5]

    joy_turbo_angular_increase:
      type: action
      interface_type: twist_mux_msgs/action/JoyTurbo
      action_name: joy_turbo_angular_increase
      buttons: [2, 4, 5]

    joy_turbo_reset:
      type: action
      interface_type: twist_mux_msgs/action/JoyTurbo
      action_name: joy_turbo_reset
      buttons: [4, 5, 7]
